- name: Manage IP blocking using iptables
  become: true
  vars:
    block_script: "{{ iptables_block_script }}"
    unblock_script: "{{ iptables_unblock_script}}"
  block:
    - name: Download CIDR file from URL
      ansible.builtin.get_url:
        url: "{{ cidr_file_url }}"
        dest: "{{ cidr_file }}"
        mode: "0644"

    - name: Filter valid CIDR lines (ignore comments and empty lines)
      ansible.builtin.shell: |
        grep -vE '^\s*(#|$)' {{ cidr_file }} > {{ cidr_file }}.filtered

    - name: Check if unblock script exists, apply it if it does
      ansible.builtin.stat:
        path: "{{ unblock_script }}"
      register: unblock_script_stat

    - name: Apply iptables unblock script if it exists
      ansible.builtin.shell: "{{ unblock_script }}"
      when: unblock_script_stat.stat.exists

    - name: Generate iptables block script
      ansible.builtin.template:
        src: iptables_block.sh.j2
        dest: "{{ block_script }}"
        mode: "0755"

    - name: Generate iptables unblock script
      ansible.builtin.template:
        src: iptables_unblock.sh.j2
        dest: "{{ unblock_script }}"
        mode: "0755"

    - name: Apply iptables block script
      ansible.builtin.shell: "{{ block_script }}"
